### ISSUE TITLE
Possible malware, do not install

### ISSUE THREAD

**Issue by quiquelhappy** [JustixDevelopment/EazyNick#17]
https://www.spigotmc.org/threads/list-of-found-malware.389467/page-41#post-4420993

**Comment by DavidCraftDev** [comment]
![Uploading E5A30036-D9FD-4ADD-AF9F-A88895B7D7ED.jpeg…]()

**Comment by DavidCraftDev** [comment]
![5BDE6A3D-FE0D-46E6-8879-633D146740C1](https://user-images.githubusercontent.com/48714689/172062786-756b77b6-04c8-48c1-8b43-6472df8af28b.jpeg)

**Comment by BossDaily** [comment]
🤥

**Comment by quiquelhappy** [comment]
Haha, yeah, no way that's accidental. It's completely not possible to do that accidentally

**Comment by GueniPlayz** [comment]
so you're saying an other person had access to your spigotmc account (because I think this is meant with "access to servers")?
If yes it's 100% your fault

**Comment by quiquelhappy** [comment]
> so you're saying an other person had access to your spigotmc account (because I think this is meant with "access to servers")?
> 
> If yes it's 100% your fault

Botnets are usually controlled by one or more master servers. This is probably what he is referring to. Either way, he coded the botnet and admitted to boundle it on the jar.

**Comment by GueniPlayz** [comment]
yeah, but how did the update got published on spigotmc?

**Comment by quiquelhappy** [comment]
> yeah, but how did the update got published on spigotmc? 

He obviously published it, he is obviously lying about doing it by accident - changing a jar boundle is not something that can be done accidentally, so he willingly coded, added and released the botnet. Pretty straightforward. Just never again trust this author and leave his media (including his Discord), he doesn't deserve any form of attention. There are plenty of similar plugins, look for another one :)

**Comment by GueniPlayz** [comment]
yeah, I recommend using NickAPI + HaoNick. Pretty good support and also a really kind moderator on their discord :)

**Comment by 2020Sanoj** [comment]
Did you even read his Statement? He wrote that others persons had acces to his server were they changed the jar, they didn't had access to his spigot account, the spigot download redircted to his website and on this server were the jars are hosted the person which had access to his server replaced his jar... There stands nothing from that this happpend accidentally or that HE published the jar with the botnet, he says after releasing it, someone who had access to his server changed the jar on the server, spigot just redirected to his website

**Comment by DavidCraftDev** [comment]
I think, the methode to download it here from  GitHub from the build with actions is secure

**Comment by GueniPlayz** [comment]
should be as the jar is only built when a new release is created, or am I wrong?

**Comment by 2020Sanoj** [comment]
The jars in the release are build if the workflow manually started, then it will be built with exact the source code of the branch selected or if the .version file gets edited

And on every commit it gets also build you can download this under "actions > Build with maven > select the commit > download the artifacty.zip"

**Comment by KektusOverflow** [comment]
@2020Sanoj What @JustixDevelopment said is not true. @quiquelhappy is telling the truth. The botnet was in there for weeks if not MONTHS!
If you look at [this](https://web.archive.org/web/20200905102802/https://github.com/JustixDevelopment/EazyNick/) capture of this repo you can see that the buildfiles are not public. Additionally there are no releases. AND nothing proves that the uploaded files on his server were from said workflow. You probably worked with Justus G. and don't want this skid to be exposed.

Please. Stop using the internet.
The world will be better.


BTW [You added the workflows yourself](https://github.com/JustixDevelopment/EazyNick/pull/11).  (This was added 18 Days ago!! The Botnet was in there for WAAAY longer.)
BTW BTW [His server has been seized by the German police lol](https://justix-dev.de/)

**Comment by 2020Sanoj** [comment]
Yes I added the files, because then we have files/jars, which aren't affected, because they got built through GitHub actions, if you want to trust the files on his (deleted) website is another question. (I simply wanted a clean file) And “my work” was only creating these workflows and telling him how to use them. I don't even know how to develop using java, I know how to use GitHub actions / docker files / batch scripting and a bit shell scripting.
If the botnet got injected by him or someone else is determined by the court.

**Comment by DavidCraftDev** [comment]
To make it more secure we also has make a PR that Change the Auto Updater to GitHub (#19)
