### ISSUE TITLE
Cloudnet

### ISSUE THREAD

**Issue by fabiandnl** [JustixDevelopment/EazyNick#36]
Hallo,
auch wenn man es in der Config aktiviert, dass der Server Cloudnet nutzt und das Nicksystem dies auch tun soll, so ändert sich beim nicken zwar der Name in der Tabmist und im Chat, allerdings nicht der Name über dem Spieler selbst. 

Ich würde mir daher wünschen, dass die Cloudnet API diesbezüglich noch weiter eingearbeitet wird.

**Comment by jgeramb** [comment]
Der Name wird nur für andere Spieler aktualisiert, nicht für dich selbst. Außerdem wird nur CloudNet v2 unterstützt, da der Support für v3 selbst nicht weiß, wie man die API benutzt.
