### ISSUE TITLE
[SUGGEST] Adding nick logs

### ISSUE THREAD

**Issue by craciu25yt** [JustixDevelopment/EazyNick#38]
That when some1 gets nicked save that as log in a file or in a db. Like that if some1 is reported or something you can know who was. Using db it can include a command like /checknick. For example: /checknick NormalNick
Justix - 15/12/22 10:43 to 12:26
CraciusConEse - 27/4/22 18:53 to 28/4/22 1:16

**Comment by jgeramb** [comment]
You can use `LogNicknames ` from the setup.yml to log the nicknames to the console. You can then just look through the log files. If you really need a database log, you can easily add it using the API: [Click here for details](https://www.justix-dev.com/docs/eazynick)
