### ISSUE TITLE
Feature Request 1

### ISSUE THREAD

**Issue by SreyasIN** [JustixDevelopment/EazyNick#8]
Please add a placeholder which returns The color of the players vault prefix when unnicked and the eazynick prefix-color when nicked.
Same goes to suffixes tooo.
Would be good for more customizatoins.

**Comment by JustixDevelopment** [comment]
> Please add a placeholder which returns The color of the players vault prefix when unnicked and the eazynick prefix-color when nicked.
> Same goes to suffixes tooo.
> Would be good for more customizatoins.

Already included. Enable ServerIsUsingVaultPrefixesAndSuffixes anf use %eazynick_chat_prefix% and %eazynick_chat_suffix%

**Comment by SreyasIN** [comment]
I mean It Return the Color Codes instead of prefix
